### ISSUE TITLE
Update package on PyPI

### ISSUE THREAD

**Issue by askerka** [rafa-acioly/animal_case#2]
Hi! Thank you for great package!
Could you please update package on PyPI?
Last version on [PyPI is 0.4.1](https://pypi.org/project/animal-case/)

**Comment by rafa-acioly** [comment]
hello @asduj, the repository that holds the code is from [dternyak](https://github.com/dternyak/animal_case).

This guy just fork my repo and published the package on pypi without my permission and "stole" the name 😢 
so i don't have permission to update it

**Comment by dternyak** [comment]
Oh hey, I'm super sorry about this. I was hacking around on the code and wanted to use it in one of my projects, so I just threw it up on pypi. 

FWIW I didn't intend to "steal" the name, there had been no package pushed to pypi for ~5 months since the last commit, and I thought this repo was no longer being maintained with there being no intention of ever publishing it on pypi.

On my fork, which kept the same licensing and attribution, I've improved the code a bit (added root `list` support, tests, and some cleanup). I'd be happy to upstream those back.

I'm happy to transfer the package if you feel strongly about the "animal_case" name, feel free to send an email (in my profile).

**Comment by rafa-acioly** [comment]
@dternyak thank you for the explanation, you can keep your repo on `pypi` with this name there is no problem.
if you for any reason can not maintain the package please let me know i'll take care of it.

**Comment by dternyak** [comment]
Thanks for understanding! Will do.

**Comment by askerka** [comment]
@rafa-acioly Hey again! I don't understand if the "original" package will appear in the PyPI under any name. Because I'm interesting in new version and it would be great see it on PyPI.

**Comment by rafa-acioly** [comment]
@dternyak can you update the package on pipy?

**Comment by jacobg** [comment]
These two repos have diverged. Is there a plan to merge them?
